config/routes.rb
Rails.application.routes.draw do
  root 'home#index'
  resources :skills, only: [:index, :show]

  get '/skills-search', to: 'skills#show'
  resources :professionals, only: [:index, :show]
  resources :requesters, only: [:show]

  resources :proposals, only: [:show] do
    resources :messages
  end

  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  get '/logout' => 'sessions#destroy'

  get '/signup' => 'users#new'
  post '/users' => 'users#create'

  namespace :admin do
    get '/dashboard', to: 'dashboard#show', as: :dashboard
    resources :users, only: [:show, :update, :destroy] do
      resources :proposals, only: [:destroy]
      resources :projects, only: [:destroy]
    end
  end

  resources :users, only: [:edit, :update, :create, :show]
  get '/confirm' => 'confirmations#new', as: :user_confirmation
  patch '/confirm' => 'confirmations#update'

  namespace :requester do
    get '/dashboard', to: "dashboard#show", as: :dashboard
    get '/proposals/:id', to: "proposals#show", as: 'proposal'
    resources :proposals, only: [:show, :edit, :update]
    get '/:project', to: "projects#show", as: 'project'
    get '/ratings', to: "ratings#new"
    post '/ratings', to: "ratings#create"
    resources :projects, only: [:new, :create, :update, :edit]
  end

  namespace :professional do
    get '/dashboard', to: 'dashboard#show', as: :dashboard
    resources :skills, only: [:new, :create, :destroy]
    resources :projects, only: [:index]
    resources :ratings, only: [:new, :create]
    get '/projects/:project', to: 'projects#show', as: 'project'
    resources :proposals, only: [:new, :create, :show, :destroy]
  end
  namespace :api, defaults: {format: :json} do
    namespace :v1 do
      resources :messages, only: [:index, :create]
    end
  end
end

app/models/project.rb
class Project < ApplicationRecord
  belongs_to :user
  has_many :proposals, dependent: :destroy
  has_many :users, through: :proposals
  has_many :messages, through: :proposals
  has_many :project_skills
  has_many :skills, through: :project_skills, dependent: :destroy

  validates :name, presence: true
  validates :user, presence: true
  validates :slug, uniqueness: true

  before_validation :generate_slug

  scope :unassigned, -> { where(status: "unassigned") }

  def generate_slug
    self.slug = "#{name.parameterize}-#{self.id}" if self.name
  end


end

app/controllers/admin/projects_controller.rb
class Admin::ProjectsController < ApplicationController

  def destroy
    project = Project.find(params[:id])
    user = User.find(params[:user_id])
    user.projects.destroy(project)
    flash[:success] = "Successfully deleted a project."
    redirect_to admin_user_path(user)
  end
end

app/controllers/professional/dashboard_controller.rb
class Professional::DashboardController < ApplicationController
  def show
    @professional = current_user
    @skills = Skill.all
    @possible_projects = User.joins(skills: :users).where("user_skills.user_id = #{current_user.id}")
  end
end

app/controllers/professional/projects_controller.rb
class Professional::ProjectsController < ApplicationController
  before_action :set_s3_direct_post, only: [:show]

  def index
    @projects = current_user.possible_projects_professional
  end

  def show
    @project = Project.find_by(slug: params[:project])
    @professional = current_user
    @rating = Rating.new 
    @message = Message.new
    @proposal = @project.proposals.assigned
  end

  private

    def set_s3_direct_post
      @s3_direct_post = S3_BUCKET.presigned_post(key: "uploads/#{SecureRandom.uuid}/${filename}", success_action_status: '201', acl: 'public-read')
    end
end

app/controllers/professional/proposals_controller.rb
class Professional::ProposalsController < ApplicationController
  before_action :set_s3_direct_post, only: [:show, :create, :new]

  def show
    @proposal = Proposal.find(params[:id])
    @message = Message.new
  end

  def new
    @proposal = Proposal.new
    @project = Project.find(params[:project])
  end

  def create
    @proposal = Proposal.new(user: current_user, project_id: params[:project_id])
    if @proposal.save
      @proposal.messages.create(image_url: params[:image_url], user_id: current_user.id)
      flash[:success] = "You have submitted a proposal for #{@proposal.project.name}"
      redirect_to professional_dashboard_path(current_user)
    else
      flash[:warning] = "Proposal not submitted, please try again."
      render :new
    end
  end

  def destroy
    proposal = Proposal.find(params[:id])
    if proposal.destroy
      current_user.proposals.delete(proposal) #if  Rails.env == "test"
      flash[:success] = "You have successfully deleted Proposal: #{proposal.id}"
    end
    redirect_to professional_dashboard_path
  end

  private

    def proposal_params
      params.require(:proposal).permit(:user_id, :project_id)
    end

    def set_s3_direct_post
      @s3_direct_post = S3_BUCKET.presigned_post(key: "uploads/#{SecureRandom.uuid}/${filename}", success_action_status: '201', acl: 'public-read')
    end

end

app/controllers/professional/ratings_controller.rb
class Professional::RatingsController < ApplicationController

  def create
    project = Project.find(params[:project])
    if Rating.find_by(user_id: params[:requester], giver_id: current_user.id)
      redirect_to "/professional/#{project.slug}"
      flash[:warning] = "Something went wrong. Please try again."
    else
      Rating.create(score: params[:rating][:score], user_id: params[:requester], giver_id: current_user.id, comment: params[:rating][:comment])
      redirect_to professional_dashboard_path(current_user)
      flash[:success] = "Thanks for rating this requester!"
    end
  end

end

app/controllers/professional/skills_controller.rb
class Professional::SkillsController < ApplicationController
  def new
    @skill = Skill.new
  end

  def create
    @skill = Skill.find(params[:skill][:skill_id])
    current_user.skills << @skill
    if @skill.save
      flash[:success] = "Created new skill!"
      redirect_to professional_dashboard_path
    end
  end

  def destroy
    skill = Skill.find(params[:id])
    current_user.skills.destroy(skill)
    flash[:info] = "Deleted a skill!"
    redirect_to professional_dashboard_path
  end
end

app/controllers/professionals_controller.rb
class ProfessionalsController < ApplicationController
  def index
    @professionals = User.professionals
  end

  def show
    @professional = User.find(params[:id])
    @skill = Skill.find(params[:skill]) if params[:skill]
  end
end

app/controllers/requester/projects_controller.rb
class Requester::ProjectsController < ApplicationController
  before_action :set_s3_direct_post, only: [:show]

  def new
    @project = Project.new
    @skills = Skill.all
  end

  def create
    @project = Project.new(project_params)
    current_user.projects << @project
    if @project.save
      flash[:success] = "Created new project: #{@project.name}!"
      redirect_to requester_dashboard_path
    else
      flash[:danger] = "The project did not create. Please try again."
      redirect_to new_requester_project_path
    end
  end

  def show
    @project = Project.find_by(slug: params[:project])
    if @project.status == "complete"
      @professional = User.find(@project.proposals.where(status: "assigned").first.user_id)
    end
    @rating = Rating.new
    @requester = current_user
    @message = Message.new
    @proposal = @project.proposals.assigned
  end

  def edit
    @project = Project.find_by(slug: params[:project])
    @project.update_attributes(status: "complete")
    redirect_to requester_dashboard_path(current_user)
  end

  def update

  end

  private

    def project_params
      params.require(:project).permit(:name, :location, :description, skill_ids: [])
    end

    def set_s3_direct_post
      @s3_direct_post = S3_BUCKET.presigned_post(key: "uploads/#{SecureRandom.uuid}/${filename}", success_action_status: '201', acl: 'public-read')
    end
end

app/views/professional/projects/_rating.html.erb
<% if @professional.not_rated?(@project.user) %>
  <h4> Rate This Requester: <%= @project.user.name %></h4>
  <%= form_for [@professional,@rating],  url: professional_ratings_path(requester: @project.user, project: @project) do |f| %>
    <%= f.label "Score" %>
    <%= f.select :score, options_for_select(1..5), include_blank: true %>
    <%= f.label "Comment" %>
    <%= f.text_area :comment %>
    <%= f.submit %>
  <% end %>
<% else %>
<p>You already rated this requester.</p>
<% end %>

app/views/professional/projects/index.html.erb
<div class="container">
  <h3>Potential Projects that Match Your Skills</h3>
  <% @projects.each do |project| %>
  <p class="potential-project"><%= link_to project.name, professional_project_path(project: project.slug)  %></p>
  <% end %>
  <hr>
  <%= link_to "Back to Your Professional Dashboard", professional_dashboard_path %>
</div>

app/views/professional/projects/show.html.erb
<div class="container">
  <div class="col-md-6 profile-card prof-project">

  <h3>Project Info:</h3>
  <p>Name: <%= @project.name %></p>
  <p>Location: <%= @project.location %></p>
  <p>Description: <%= @project.description %></p>
  <p>Status: <%= @project.status %></p>
  <p>Project Date: <%= @project.created_at %></p>
  <p>Requester: <%= link_to @project.user.name, requester_path(@project.user) %> (Rating: <%= @project.user.average_rating if @project.user.average_rating %>) </p>
  <p>Required Skills:
    <% @project.skills.each do |skill| %>
      <%= skill.name%>
    <% end %></p>

  <% if @project.status == "unassigned" %>
    <%= link_to "Create a Proposal", new_professional_proposal_path(project: @project.id), class: "btn btn-warning" %>
  <% end %>

  <% if @project.status == "complete" %>
  <%= render partial: "rating" %>
  <% end %>


  <p><%= link_to "Back to Your Professional Dashboard", professional_dashboard_path %></p>

  </div>
  <% unless @project.status == "unassigned" %>
    <%= render partial: "shared/message_center" %>
  <% end %>

</div>