config/routes.rb
Rails.application.routes.draw do
  root 'home#index'
  resources :skills, only: [:index, :show]

  get '/skills-search', to: 'skills#show'
  resources :professionals, only: [:index, :show]
  resources :requesters, only: [:show]

  resources :proposals, only: [:show] do
    resources :messages
  end

  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  get '/logout' => 'sessions#destroy'

  get '/signup' => 'users#new'
  post '/users' => 'users#create'

  namespace :admin do
    get '/dashboard', to: 'dashboard#show', as: :dashboard
    resources :users, only: [:show, :update, :destroy] do
      resources :proposals, only: [:destroy]
      resources :projects, only: [:destroy]
    end
  end

  resources :users, only: [:edit, :update, :create, :show]
  get '/confirm' => 'confirmations#new', as: :user_confirmation
  patch '/confirm' => 'confirmations#update'

  namespace :requester do
    get '/dashboard', to: "dashboard#show", as: :dashboard
    get '/proposals/:id', to: "proposals#show", as: 'proposal'
    resources :proposals, only: [:show, :edit, :update]
    get '/:project', to: "projects#show", as: 'project'
    get '/ratings', to: "ratings#new"
    post '/ratings', to: "ratings#create"
    resources :projects, only: [:new, :create, :update, :edit]
  end

  namespace :professional do
    get '/dashboard', to: 'dashboard#show', as: :dashboard
    resources :skills, only: [:new, :create, :destroy]
    resources :projects, only: [:index]
    resources :ratings, only: [:new, :create]
    get '/projects/:project', to: 'projects#show', as: 'project'
    resources :proposals, only: [:new, :create, :show, :destroy]
  end
  namespace :api, defaults: {format: :json} do
    namespace :v1 do
      resources :messages, only: [:index, :create]
    end
  end
end

app/models/project.rb
class Project < ApplicationRecord
  belongs_to :user
  has_many :proposals, dependent: :destroy
  has_many :users, through: :proposals
  has_many :messages, through: :proposals
  has_many :project_skills
  has_many :skills, through: :project_skills, dependent: :destroy

  validates :name, presence: true
  validates :user, presence: true
  validates :slug, uniqueness: true

  before_validation :generate_slug

  scope :unassigned, -> { where(status: "unassigned") }

  def generate_slug
    self.slug = "#{name.parameterize}-#{self.id}" if self.name
  end


end

app/controllers/admin/projects_controller.rb
class Admin::ProjectsController < ApplicationController

  def destroy
    project = Project.find(params[:id])
    user = User.find(params[:user_id])
    user.projects.destroy(project)
    flash[:success] = "Successfully deleted a project."
    redirect_to admin_user_path(user)
  end
end

app/controllers/professional/projects_controller.rb
class Professional::ProjectsController < ApplicationController
  before_action :set_s3_direct_post, only: [:show]

  def index
    @projects = current_user.possible_projects_professional
  end

  def show
    @project = Project.find_by(slug: params[:project])
    @professional = current_user
    @rating = Rating.new 
    @message = Message.new
    @proposal = @project.proposals.assigned
  end

  private

    def set_s3_direct_post
      @s3_direct_post = S3_BUCKET.presigned_post(key: "uploads/#{SecureRandom.uuid}/${filename}", success_action_status: '201', acl: 'public-read')
    end
end

app/controllers/requester/dashboard_controller.rb
class Requester::DashboardController < ApplicationController

  def show
    @user = current_user
  end
end

app/controllers/requester/projects_controller.rb
class Requester::ProjectsController < ApplicationController
  before_action :set_s3_direct_post, only: [:show]

  def new
    @project = Project.new
    @skills = Skill.all
  end

  def create
    @project = Project.new(project_params)
    current_user.projects << @project
    if @project.save
      flash[:success] = "Created new project: #{@project.name}!"
      redirect_to requester_dashboard_path
    else
      flash[:danger] = "The project did not create. Please try again."
      redirect_to new_requester_project_path
    end
  end

  def show
    @project = Project.find_by(slug: params[:project])
    if @project.status == "complete"
      @professional = User.find(@project.proposals.where(status: "assigned").first.user_id)
    end
    @rating = Rating.new
    @requester = current_user
    @message = Message.new
    @proposal = @project.proposals.assigned
  end

  def edit
    @project = Project.find_by(slug: params[:project])
    @project.update_attributes(status: "complete")
    redirect_to requester_dashboard_path(current_user)
  end

  def update

  end

  private

    def project_params
      params.require(:project).permit(:name, :location, :description, skill_ids: [])
    end

    def set_s3_direct_post
      @s3_direct_post = S3_BUCKET.presigned_post(key: "uploads/#{SecureRandom.uuid}/${filename}", success_action_status: '201', acl: 'public-read')
    end
end

app/controllers/requester/proposals_controller.rb
class Requester::ProposalsController < ApplicationController
  before_action :set_s3_direct_post, only: [:show]

  def edit
    @proposal = Proposal.find(params[:id])
    project = @proposal.project_id
    @proposal.update_attributes(status: "assigned")
    Project.find(project).update_attributes(status: "assigned")
    redirect_to "/requester/dashboard"
    flash[:success] = "You successfully awarded this project to a professional!"
  end

  def update

  end

  def show
    @proposal = Proposal.find(params[:id])
    @message = Message.new
  end

  private

    def set_s3_direct_post
      @s3_direct_post = S3_BUCKET.presigned_post(key: "uploads/#{SecureRandom.uuid}/${filename}", success_action_status: '201', acl: 'public-read')
    end
end

app/controllers/requester/ratings_controller.rb
class Requester::RatingsController < ApplicationController

  def create
    project = Project.find(params[:project])
    if Rating.find_by(user_id: params[:professional], giver_id: current_user.id)
      redirect_to "/requester/#{project.slug}"
      flash[:warning] = "Something went wrong. Please try again."
    else
      Rating.create(score: params[:rating][:score], user_id: params[:professional], giver_id: current_user.id, comment: params[:rating][:comment])
      redirect_to requester_dashboard_path(current_user)
      flash[:success] = "Thanks for rating this professional!"
    end
  end

end

app/controllers/requesters_controller.rb
class RequestersController < ApplicationController

  def show
    @requester = User.find(params[:id])
  end

end

app/views/requester/projects/new.html.erb
<div class="row">
  <div class="form">
    <div class="col-md-4 col-md-offset-4">
      <h2>Create a new project:</h2>
      <%= form_for [:requester, @project] do |f| %>
        <%= f.label :name %>
        <%= f.text_field :name %>
        <%= f.label :location %>
        <%= f.text_field :location %>
        <%= f.label :description %>
        <%= f.text_area :description %>

        <div class="row">
          <% @skills.each do |skill| %>
            <div class="col-md-4">
              <%= label_tag skill.name %>
              <%= check_box_tag(:skill_id, skill.id, false, name: "project[skill_ids][]", id: "skill-#{skill.id}", include_blank: true) %>
            </div>
          <% end %>
        </div>

        <%= f.submit("Create Project") %>
      <% end %>
    </div>
  </div>
</div>

app/views/requester/projects/show.html.erb
<div class="container">
  <div class="col-md-6 profile-card proposal-spacer">
    <h1><%= @project.name %></h1>
    <h3>Status: <%= @project.status.capitalize %></h3>

    <%= @project.location %>

    <%= @project.status %>

    <% if @project.status == "assigned" %>
      <%= link_to "Mark This Project as Complete", edit_requester_project_path(current_user, project: @project.slug), method: :get %>
    <% end %>

    <% if @project.status == "complete" && @requester.not_rated?(@professional) %>
    <span id=rate-header> <h4>Rate This Professional:</h4>
    <h4><%= link_to @professional.name, professional_path(@professional) %></h4></span>
     <%= form_for [@requester,@rating],  url: requester_ratings_path(professional: @professional, project: @project) do |f| %>
       <%= f.label "Score" %>
       <%= f.select :score, options_for_select(1..5), include_blank: true %>
       <%= f.label "Comment" %>
       <%= f.text_area :comment %>
       <%= f.submit %>
    <% end %>
    <% end %>
  <% @project.proposals.each do |proposal| %>
  <p>Proposal ID: <%= link_to proposal.id, requester_proposal_path(proposal) %></p>
  <p>From: <%= proposal.user.name %></p>
  <%= proposal.status %>
  <% end %>
  </div>
  <% unless @project.status == "unassigned" %>
    <%= render partial: "shared/message_center" %>
  <% end %>
</div>