config/routes.rb
Rails.application.routes.draw do
  root 'home#index'
  resources :skills, only: [:index, :show]

  get '/skills-search', to: 'skills#show'
  resources :professionals, only: [:index, :show]
  resources :requesters, only: [:show]

  resources :proposals, only: [:show] do
    resources :messages
  end

  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  get '/logout' => 'sessions#destroy'

  get '/signup' => 'users#new'
  post '/users' => 'users#create'

  namespace :admin do
    get '/dashboard', to: 'dashboard#show', as: :dashboard
    resources :users, only: [:show, :update, :destroy] do
      resources :proposals, only: [:destroy]
      resources :projects, only: [:destroy]
    end
  end

  resources :users, only: [:edit, :update, :create, :show]
  get '/confirm' => 'confirmations#new', as: :user_confirmation
  patch '/confirm' => 'confirmations#update'

  namespace :requester do
    get '/dashboard', to: "dashboard#show", as: :dashboard
    get '/proposals/:id', to: "proposals#show", as: 'proposal'
    resources :proposals, only: [:show, :edit, :update]
    get '/:project', to: "projects#show", as: 'project'
    get '/ratings', to: "ratings#new"
    post '/ratings', to: "ratings#create"
    resources :projects, only: [:new, :create, :update, :edit]
  end

  namespace :professional do
    get '/dashboard', to: 'dashboard#show', as: :dashboard
    resources :skills, only: [:new, :create, :destroy]
    resources :projects, only: [:index]
    resources :ratings, only: [:new, :create]
    get '/projects/:project', to: 'projects#show', as: 'project'
    resources :proposals, only: [:new, :create, :show, :destroy]
  end
  namespace :api, defaults: {format: :json} do
    namespace :v1 do
      resources :messages, only: [:index, :create]
    end
  end
end

app/views/shared/_message_center.html.erb
<div class="col-md-4 message-center form pull-right">

  <h3>Message Center</h3>
  <%= form_for([@proposal, @message], html: { class: "directUpload", data: {'form-data' => (@s3_direct_post.fields), 'url' => @s3_direct_post.url, 'host' => URI.parse(@s3_direct_post.url).host} }) do |f|%>
    <%= f.label "Add a message" %>
    <%= f.text_area :body %>
    <%= f.label "Add a file" %>
    <%= f.file_field :image_url %>
    <%= f.submit("Submit") %>
  <% end %>
  <hr>
  <% @proposal.messages_by_most_recent.each do |message| %>
    <div id="message-<%= message.id %>" class="panel">
      <% if message.body %>
        <p><%= message.body %></p>
      <% end %>
      <% if message.image_url %>
        <a href=<%= message.image_url %>>
          <%= image_or_pdf_icon(message.image_url) %>
        </a>
      <% end %>
      <p>Sent by <%= message.user.name %> at <%= message.created_at %></p>
      <% if message.user == current_user %>
        <%= link_to "Edit", edit_proposal_message_path(@proposal, message), class: "btn btn-warning btn-xs" %>
        <%= link_to "Delete", proposal_message_path(@proposal, message), method: :delete, class: "btn btn-danger btn-xs" %>
      <% end %>
    </div>
  <% end %>
</div>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-default custom-nav">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
       <%= image_tag("pushpin-orange.png", class: "pinpic") %> <%= link_to "PushPin", root_path, class: "navbar-brand" %>
    </div>

    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Browse Professionals", professionals_path %></li>
        <% if current_user %>
        <li><%= link_to "Logout", logout_path %></li>
        <% else %>
        <li><%= link_to "Login", login_path %></li>
        <li><%= link_to "Signup", signup_path %></li>
        <% end %>
        <% if current_user %>
          <li class="dropdown">
            <a href="#" id="dropdown-thing" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><img src=<%= current_user.image %> alt="user_image" class="nav-user-icon" /></a>
            <ul class="dropdown-menu">
              <% if current_user.professional? %>
                <li><%= link_to "Professional Dashboard", professional_dashboard_path %></li>
              <% end %>
              <% if current_user.admin? %>
                <li><%= link_to "Admin Dashboard", admin_dashboard_path %></li>
              <% end %>
              <% if current_user.requester? %>
                <li><%= link_to "Requester Dashboard", requester_dashboard_path %></li>
              <% end %>
              <li role="separator" class="divider"></li>
              <li><%= link_to "Settings", user_path(current_user) %></li>
            </ul>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>