config/routes.rb
Rails.application.routes.draw do
  root 'home#index'
  resources :skills, only: [:index, :show]

  get '/skills-search', to: 'skills#show'
  resources :professionals, only: [:index, :show]
  resources :requesters, only: [:show]

  resources :proposals, only: [:show] do
    resources :messages
  end

  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  get '/logout' => 'sessions#destroy'

  get '/signup' => 'users#new'
  post '/users' => 'users#create'

  namespace :admin do
    get '/dashboard', to: 'dashboard#show', as: :dashboard
    resources :users, only: [:show, :update, :destroy] do
      resources :proposals, only: [:destroy]
      resources :projects, only: [:destroy]
    end
  end

  resources :users, only: [:edit, :update, :create, :show]
  get '/confirm' => 'confirmations#new', as: :user_confirmation
  patch '/confirm' => 'confirmations#update'

  namespace :requester do
    get '/dashboard', to: "dashboard#show", as: :dashboard
    get '/proposals/:id', to: "proposals#show", as: 'proposal'
    resources :proposals, only: [:show, :edit, :update]
    get '/:project', to: "projects#show", as: 'project'
    get '/ratings', to: "ratings#new"
    post '/ratings', to: "ratings#create"
    resources :projects, only: [:new, :create, :update, :edit]
  end

  namespace :professional do
    get '/dashboard', to: 'dashboard#show', as: :dashboard
    resources :skills, only: [:new, :create, :destroy]
    resources :projects, only: [:index]
    resources :ratings, only: [:new, :create]
    get '/projects/:project', to: 'projects#show', as: 'project'
    resources :proposals, only: [:new, :create, :show, :destroy]
  end
  namespace :api, defaults: {format: :json} do
    namespace :v1 do
      resources :messages, only: [:index, :create]
    end
  end
end

app/controllers/admin/dashboard_controller.rb
class Admin::DashboardController < ApplicationController
  def show
    @users = User.all.sort
  end
end

app/controllers/professional/dashboard_controller.rb
class Professional::DashboardController < ApplicationController
  def show
    @professional = current_user
    @skills = Skill.all
    @possible_projects = User.joins(skills: :users).where("user_skills.user_id = #{current_user.id}")
  end
end

app/controllers/requester/dashboard_controller.rb
class Requester::DashboardController < ApplicationController

  def show
    @user = current_user
  end
end

app/controllers/requester/projects_controller.rb
class Requester::ProjectsController < ApplicationController
  before_action :set_s3_direct_post, only: [:show]

  def new
    @project = Project.new
    @skills = Skill.all
  end

  def create
    @project = Project.new(project_params)
    current_user.projects << @project
    if @project.save
      flash[:success] = "Created new project: #{@project.name}!"
      redirect_to requester_dashboard_path
    else
      flash[:danger] = "The project did not create. Please try again."
      redirect_to new_requester_project_path
    end
  end

  def show
    @project = Project.find_by(slug: params[:project])
    if @project.status == "complete"
      @professional = User.find(@project.proposals.where(status: "assigned").first.user_id)
    end
    @rating = Rating.new
    @requester = current_user
    @message = Message.new
    @proposal = @project.proposals.assigned
  end

  def edit
    @project = Project.find_by(slug: params[:project])
    @project.update_attributes(status: "complete")
    redirect_to requester_dashboard_path(current_user)
  end

  def update

  end

  private

    def project_params
      params.require(:project).permit(:name, :location, :description, skill_ids: [])
    end

    def set_s3_direct_post
      @s3_direct_post = S3_BUCKET.presigned_post(key: "uploads/#{SecureRandom.uuid}/${filename}", success_action_status: '201', acl: 'public-read')
    end
end

app/controllers/requester/proposals_controller.rb
class Requester::ProposalsController < ApplicationController
  before_action :set_s3_direct_post, only: [:show]

  def edit
    @proposal = Proposal.find(params[:id])
    project = @proposal.project_id
    @proposal.update_attributes(status: "assigned")
    Project.find(project).update_attributes(status: "assigned")
    redirect_to "/requester/dashboard"
    flash[:success] = "You successfully awarded this project to a professional!"
  end

  def update

  end

  def show
    @proposal = Proposal.find(params[:id])
    @message = Message.new
  end

  private

    def set_s3_direct_post
      @s3_direct_post = S3_BUCKET.presigned_post(key: "uploads/#{SecureRandom.uuid}/${filename}", success_action_status: '201', acl: 'public-read')
    end
end

app/controllers/requester/ratings_controller.rb
class Requester::RatingsController < ApplicationController

  def create
    project = Project.find(params[:project])
    if Rating.find_by(user_id: params[:professional], giver_id: current_user.id)
      redirect_to "/requester/#{project.slug}"
      flash[:warning] = "Something went wrong. Please try again."
    else
      Rating.create(score: params[:rating][:score], user_id: params[:professional], giver_id: current_user.id, comment: params[:rating][:comment])
      redirect_to requester_dashboard_path(current_user)
      flash[:success] = "Thanks for rating this professional!"
    end
  end

end

app/controllers/requesters_controller.rb
class RequestersController < ApplicationController

  def show
    @requester = User.find(params[:id])
  end

end

app/views/requester/dashboard/show.html.erb
<div class="dashboard-container dashboard-header">
  <div class="container text-center">
    <h1>Welcome to Your Requester Dashboard</h1>
    <%= link_to "Create New Project", new_requester_project_path, class: "btn btn-primary btn-lg prof-btn" %>
  </div>
</div>
<div class="container">
  <div class="row" id="current-projects">
    <h4>Current Projects</h4>
    <% @user.current_projects.each_with_index do |project, index| %>
    <a href=<%= requester_project_path(project: project.slug) %> >
      <div class="col-md-3 profile-card">
        <h5><%= project.name %></h5>
        <p>Status: <%= project.status.capitalize %></p>
        <p>Location: <%= project.location %></p>
        <p>Description: <%= project.description %></p>
        <p>Project ID: <%= project.id %></p>
          <% if project.status == "assigned" %>
          Professional: <%= project.proposals.where(status: "assigned").first.user_id %>
          <% end %>
      </div>
    </a>
    <% if (index +1) % 4 == 0 %>
      <div class="clearfix"></div>
    <% end %>
    <% end %>
  </div>
</div>
<div class="container">
  <div class="row" id="proposals">
    <h4>Proposals</h4>
    <% @user.projects.unassigned.each do |project| %>
    <% project.proposals.unassigned.each_with_index do |proposal, index| %>
        <div class="col-md-3 profile-card">
          <h5>Proposal ID: <%= link_to proposal.id, requester_proposal_path(proposal) %> for project <%= proposal.project_id %> </h5>
          <p>Proposed by: <%= proposal.user.name %></p>
          <p>Status: <%= proposal.status %></p>
        </div>
        <% if (index + 1) % 4 == 0 %>
          <div class="clearfix"> </div>
        <% end %>
      <% end %>
    <% end %>
  </div>
</div>
<div class="container">
  <div class="row" id="completed-projects">
    <h4>Project History</h4>
    <% @user.completed_projects.each_with_index do |project, index| %>
    <a href=<%= requester_project_path(project: project.slug) %> >
      <div class="col-md-3 profile-card">

        <h5><%= project.name %></h5>
        <p>Status: <%= project.status %></p>
        <p>Location: <%= project.location %></p>
        <p>Description: <%= project.description %></p>
      </div>
    </a>
      <% if (index + 1) % 4 == 0 %>
        <div class="clearfix"> </div>
      <% end %>
    <% end %>
  </div>
</div>